# IOC device settings, YAML
# With exception of 'general', each top level key defines a new ioc for that device
general:
  prefix: TGT:ATST
  log_dir: 'logs'   # path of logs directory
  epics_addr_list: 'None'
  delay: 0.5
lakeshore_218:  # Lakeshore RS232: 7 data bits, Odd parity, 1 stop bit
  module: 'devices.ls218'
  autostart: True          # Should IOC Manager try to start this?
  ip: '192.168.2.1'
  port: '23'    # channel 1 of serial to ethernet
  timeout: 2
  delay: 10
  channels: # List of PV names for each read channel of 218 in order
    - Test_TI
    - None
    - None
    - None
    - None
    - None
    - None
    - None
  records:
    Test_TI:
      DESC: 'Test Resistor'
      PREC: 2
      EGU: 'K'
      HIHI: 310
      HIGH: 300
      LOW: 2
      LOLO: 1
dat8024:
  module: 'devices.dat8024'
  autostart: True          # Should IOC Manager try to start this?
  ip: '192.168.1.12'
  port: '502'
  timeout: 2
  delay: 5
  channels: # List of channel names in order. None indicates unused channel.
    - Voltage1_VC
    - None
    - None
    - None
  records:
    Voltage1_VC:
      DESC: 'DAC Output 1'
      PREC: 3
      EGU: 'V'
      DRVH: 5
      DRVL: 0
      HIHI: 6
      HIGH: 5.5
      LOW: -1
      LOLO: -2
dat8017_v:
  module: 'devices.dat8017'
  autostart: True
  ip: '192.168.1.11'
  port: '502'
  timeout: 2
  delay: 5
  channels: # List of PV names for each read channel of datexel in order
    - Voltage1_VI
  calibration:
    Voltage1_VI: 1
  records:
    Voltage1_VI:
      DESC: 'Voltage In'
      PREC: 3
      EGU: 'V'
      HIHI: 5
      HIGH: 5
      LOW: .01
      LOLO: 0